### ISSUE TITLE
[question] what's a good way to chain more than one effect?

### ISSUE THREAD

**Issue by moebiussurfing** [npisanti/ofxDotFrag#1]
hey @npisanti, thanks for sharing this. it looks really good.
Do we need to use several fbo's to chain the fx?
and how it could be a good way to change/browse around all the effects in one frag only.

**Comment by npisanti** [comment]
you can just use one ofFbo and then use `frag.apply( fbo )`, for example
```cpp
fbo.begin();
    ofClear( 0, 0, 0, 0 );
    // drawing some stuff here 
fbo.end();

frag.apply( fbo );
another_frag.apply( fbo );
still_another_frag.apply( fbo );
```

for the second question, probably ofxDotFrag isn't the best thing if you have to have all the frag available and switch between them, because each ofxDotFrag has an internal fbo for rendering and then it get rerendered on the processed fbo, it's to make easy the chaining process ( so you can just use `.apply( fbo )` and you're done ). 

So having lots of ofxDotFrags classes would mean having lots of allocated fbo that don't get used, in that case it would be better to just use two `ofFbo` and many `ofShader` and render from one of them to the other, it would be both more efficient in processing time and used memory, i made something like that here 
https://github.com/npisanti/np-tools/tree/master/pixelscript/src
check the files `FileWatcher`, `Shader`, and `Buffer`

**Comment by moebiussurfing** [comment]
thanks for your explanation @npisanti , it helped me to learn a bit more about this topic.

The above link doesn't work... But I understand that you say that:

If I want to chain, for example, HSB, Monochrome and ThreeTones shaders,
I should combine the 3 .h/.cpp into one single file?

About the "efficient in processing" do you mean it's important for lower platforms like RPi or in a big system with dedicated GPU too?

There's a limit about how may FBO's to use at the same time? 
I think you referred to the GPU memory for the FBO texture... but also for the performance of the shaders...

**Comment by npisanti** [comment]
this is a working link, i've moved things around a bit:
https://github.com/npisanti/np-pixelscript/tree/master/src/pixelscript

in this case you have a class to manage the fbos for rendering, and you should use 3 different .frag files, not 3 .h/.cpp, you jus use 3 `ofShader` 

in the past i've found there is a limit to the number of fbos a weaker machine could allocate, expecially rpi and machines with integrated intel graphics. So reducing the number of used fbo could be important in those cases.

It also reduces the amount of times the shader is rendered to the fbo, in ofxDotFrag you render to the internal fbo and the re-render to the fbo to process for each used shader. Using just two fbos instead, rendering from one to the other and drawing the last used fbo to screen is more efficient, but doing it like this into ofxDotFrag would lead to the need to a total rewrite of the API.
